### ISSUE TITLE
Crashes, dark mode not working

### ISSUE THREAD

**Issue by ghost** [sharn25/MovieTV-DL#2]
Whenever I try to skip a few minutes in a movie, the app suddenly crashes. In addition, the theme for the app seems to be stuck on light even though I selected dark.

**Comment by sharn25** [comment]
It’s limitation with the links. Try downloading.
After selecting dark mode and clicking save button restart the app

**Comment by sharn25** [comment]
Please close the issue if you got the dark theme working.
